baseURL = "https://projects.metio.wtf/krei/"
languageCode = "en"
theme = "metio"
title = "krei"

pygmentsUseClasses=true
sectionPagesMenu = "main"
enableRobotsTXT = true
DefaultContentLanguage = "en"
