package wtf.metio.krei.usecase;

import wtf.metio.krei.model.Project;
import wtf.metio.krei.model.Unit;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;

import static java.lang.String.join;
import static java.nio.charset.StandardCharsets.UTF_8;
import static java.nio.file.StandardOpenOption.APPEND;
import static java.nio.file.StandardOpenOption.CREATE;
import static java.util.stream.Stream.of;

public final class CreateShellScript {

    public static void execute(final Project project, final Path target) {
        execute(project, target, "#!/bin/sh");
    }

    public static void execute(final Project project, final Path target, final String shebang) {
        write(target, shebang);
        write(target, "");
        write(target, "# generated by krei");
        write(target, "# https://codeberg.org/metio.wtf/krei/");
        write(target, "");
        Executor.execute(project, exec -> write(target, exec));
    }

    private static void write(final Path target, final String exec) {
        try {
            Files.writeString(target, exec + System.lineSeparator(), UTF_8, CREATE, APPEND);
        } catch (final IOException exception) {
            throw new RuntimeException(exception);
        }
    }

    private CreateShellScript() {
        // entry point
    }

}
