FROM openjdk:14

LABEL org.opencontainers.image.authors="Sebastian Hoß <seb@hoß.de>"
LABEL org.opencontainers.image.vendor="metio.wtf"
LABEL org.opencontainers.image.url="https://krei.projects.metio.wtf/"
LABEL org.opencontainers.image.title="krei-build-env"
LABEL org.opencontainers.image.description="Image which contains all required software to build the entire krei project"
