name: Perform Release
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # SonarQube: Disabling shallow clone is recommended for improving relevancy of reporting
          # Hugo: Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create release version
        id: release
        run: echo "::set-output name=version::$(date +'%Y.%m.%d-%H%M%S')"
      - name: Set release version
        run: mvn --batch-mode versions:set -DnewVersion=${{steps.release.outputs.version}} -DgenerateBackupPoms=false
      - name: Verify Project
        run: mvn --batch-mode --settings $GITHUB_WORKSPACE/build/settings.xml --activate-profiles sonar verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Website
        run: hugo --source krei-docs --minify --i18n-warnings
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./krei-docs/public
          force_orphan: true
          cname: projects.metio.wtf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.release.outputs.version}}
          release_name: Release ${{steps.release.outputs.version}}
          draft: false
          prerelease: false
          body: |
            Automated release, see [commits](https://github.com/metio/krei/commits/${{steps.release.outputs.version}}) for changes.

            Include this project as a dependency:
            ```xml
            <dependency>
              <groupId>wtf.metio.krei</groupId>
              <artifactId>krei</artifactId>
              <version>${{steps.release.outputs.version}}</version>
            </dependency>
            ```
